### ISSUE TITLE
TvFocusGuideView implementations/limitations? (discussion/question)

### ISSUE THREAD

**Issue by olafurnsig** [react-native-tvos/react-native-tvos#103]
Not a bug, just a discussion.

I'm trying to work a TvFocusGuideView into a permanent Side-drawer from react-navigation (not native-navigation).

I'm running into an error:

`Exception thrown while executing UI block: NSLayoutConstraint for <NSLayoutYAxisAnchor:0x282150040 "UIFocusGuide:0x28077cd20''.top">: A constraint cannot be made from <NSLayoutYAxisAnchor:0x282150040 "UIFocusGuide:0x28077cd20''.top"> to a constant. Location anchors require being paired.`

Has it something to do with absolute positioning?

I've already implemented one TvFocusGuideView on a screen and it works as expected, however putting one in the Sidedrawer is stumping me a bit.

**Comment by olafurnsig** [comment]
Oh, actually I got it working.

The error is hard to make sense of though.

**Comment by dlowder-salesforce** [comment]
@olafurnsig also take a look at #101 .... hopefully this will lead to better alignment between the focus APIs for tvOS and Android TV

**Comment by dlowder-salesforce** [comment]
Also yes, there have been issues reported where a view with absolute position can't get focus ( see#71 ).  However, constraint errors shouldn't prevent the view from showing and from getting focus. @ndillon1 did you see this error?

**Comment by olafurnsig** [comment]
It seems that I run into that error above when trying to use the TVFocusGuideView on a react-navigation screen that isn't initially mounted.

App starts on Screen A (which has TvFocusGuideView - works fine)
Navigate to Screen B (which has TvFocusGuideVIew - error above appears).

**Comment by olafurnsig** [comment]
Haven't tried this out on a production build - however I run into this error 10 times more often if I'm running remote debugging with the RN Debugger, If I'm not using the remote debugging, this happens way less.

**Comment by dlowder-salesforce** [comment]
Seems like refs are changing, or not yet valid, when the focus guide is mounting.  Do you have JS code (or better yet, a test project), that shows this error?

**Comment by olafurnsig** [comment]
I can try to create some sort of mini-project to reproduce this in a few days.

There could be multiple reasons for this in my code somehow - I've got a typescript version of the TVFGV example as a navigation screen, and I don't get this issue when I navigate to it.

This is a part of one of my files that gets the error .. sometimes, and most often when running the remote debugger. It's wrapped a redux connect function which loads in the data. The TVFocusGuideView component isn't rendered until the data has actually arrived.

```
  constructor(props: any) {
    super(props);
   .....

    this.buttonInHeroContainer = React.createRef() as any;
  }

  private buttonInHeroContainer: any;
```

```
public render() {
    return (
      <View style={styles.container}>
        <ImageBackground
          source={{
            uri:
              backdropUri !== ''
                ? getImageWithImageKit(backdropUri, 1080, 1920, 60)
                : '',
          }}
          style={{ width: 1920, height: 1080 }}
        >
          <LinearGradient
            locations={[0, 0.7]}
            colors={[ColorScheme.transparent, ColorScheme.almostBlack]}
            style={[
              {
                backgroundColor: ColorScheme.transparent,
                position: 'absolute',
                top: 0,
                height: '100%',
                left: 0,
                right: 0,
                zIndex: 2,
                flex: 1,

                paddingLeft: 20,
              },
              { height: 1080, width: 1920 },
            ]}
          >
            <ScrollView>
              {this.renderHeroInfo()}
              {this.renderCarousels()}
            </ScrollView>
          </LinearGradient>
        </ImageBackground>
      </View>
    );
```

 ```
 private renderHeroInfo = () => {
    const { heroCarouselItem } = this.state;

    if (heroCarouselItem) {
      return (
        <TVFocusGuideView
          style={{}}
          destinations={[this.buttonInHeroContainer]}
        >
          <View
            style={{
              paddingLeft: 20,
              maxWidth: '60%',
              marginBottom: 30,
              paddingTop: '10%',
            }}
          >
            <View style={{}}>
              <Text style={{ fontSize: 80 }}>{heroCarouselItem.title}</Text>
              <Text style={{ fontSize: 28 }}>
                {heroCarouselItem.description}
              </Text>

              <TouchableOpacity
                ref={(component) => (this.buttonInHeroContainer = component)}
                onPress={() => {}}
                style={styles.heroButton}
                hasTVPreferredFocus={true}
              >
                <Text style={styles.buttonText}>View</Text>
              </TouchableOpacity>
            </View>
          </View>
        </TVFocusGuideView>
      );
    }
  };
```

**Comment by olafurnsig** [comment]
It seems that having some logic in componentDidMount that takes more than a few milliseconds, and possibly delay the initial render of a component, can cause the TvFocusGuideView to get an error, since it possibly delays the ref being created.

If I delay any logic in componentDidMount by a second, I don't run into an error, If I don't delay it I get an error.

**Comment by raytiley** [comment]
@olafurnsig - how did you get the permant side drawer items to be focusable if you don't mind me asking?

**Comment by olafurnsig** [comment]
@raytiley I'm using a custom component passed to `drawerContent`.

I still have the slight issue of not being able to navigate to the side drawer unless theres a corresponding touchable on the screen that the user can hop left from, hence my attempt at using TvFocusGuideView there, but it seems something about how it's created causes TVFGV to have issues.

**Comment by jasmeet447** [comment]
Hi @olafurnsig, I've been using the focus guide in my react-native-tvos project and I'm using similar errors while implementing the focus guide. I dont know why this happens as the date comes from back-end api and re rendering causes it to crash several times. Any help will be appreciated

**Comment by olafurnsig** [comment]
@jasmeet447 - What I've found to work, for reasons unknown - is to delay any data fetching your doing just for 250-300ms by using setTimeout, since doing that I've stopped running into that issue.

**Comment by dlowder-salesforce** [comment]
Since refs aren't available until render, I use the technique shown in `RNTester/js/examples/TVFocusGuide/TVFocusGuideExample.js`, where there is a state `ref`, and the focus guide is written something like this:

```js

renderFocusGuide() {
  const destinations = this.state.ref ? [this.state.ref] : [];
  return (
    <TVFocusGuide destinations={destinations} />
  );
}
```

That way the focus guide destinations are always valid.

**Comment by olafurnsig** [comment]
@dlowder-salesforce -  Am I misunderstanding the concept of the TVFG, doesn't it need to wrap the Touchables as a container to be able to redirect to it?

I have implemented a few TVFGV in my app, but each one has been a really slow process of trial and error.

But I've still run into issues by creating the TVFG with a similar way as you describe there.

For example, I have a component where the TvFocusGuideView is conditionally rendered as a different component, even if I initialise the TVFGV with `destinations={[]}` it still throws the error below.



```
2020-10-16 09:44:31.222695+0000 appName[1957:1739552] A constraint factory method was passed a nil layout anchor.  This is not allowed, and may cause confusing exceptions. Break on BOOL _NSLayoutConstraintToNilAnchor(void) to debug.  This will be logged only once.  This may break in the future.
2020-10-16 09:44:31.223027+0000 appName[1957:1739552] [native] Error setting property 'destinationTags' of RCTTVFocusGuideView with tag #8989: Exception thrown while executing UI block: NSLayoutConstraint for <NSLayoutYAxisAnchor:0x281ed5b80 "UIFocusGuide:0x283bc71b0''.top">: A constraint cannot be made from <NSLayoutYAxisAnchor:0x281ed5b80 "UIFocusGuide:0x283bc71b0''.top"> to a constant. Location anchors require being paired.
```

**Comment by olafurnsig** [comment]
BTW - with all the discussions happening in issues here, I wonder if a Slack space for this project would be a good idea, since react native tvOS development is a bit of a wild west thing and many questions surround it :)

**Comment by jasmeet447** [comment]
@olafurnsig, I've been running into some similar kind of issues that I get unexplained crashes for the constraints of focus guide here and there. What I've made sure of two things while implementing the TVFGV: 
1. Refs for the destinations exist
2. TVFGV renders after all the components have been rendered, by maintaining a state variable for the focus guide.
It saves a lot of effort. Still getting these errors sometimes is quite irritating 😅

**Comment by iamcam** [comment]
Is there anything consistent between these that cause the error? We're seeing the same thing when attempting to encompass a carousel component (which I believe is more or less a horizontal FlatList) inside a FlatList item. We have other FlatList items rendering properly when they don't have the more complex subviews.

**Comment by dlowder-salesforce** [comment]
On Apple TV, the focus guide attempts to size itself to its containing view.  See the `addFocusGuide()` method in 

https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.63.1/React/Views/RCTTVFocusGuideView.m

I suspect the problem seen by @olafurnsig is related to that.  That code was added to solve some other issues where the focus guide would render with zero size.  It may be helpful to make sure that the focus guide's parent is a plain `View`, if that is possible in your design.
