### ISSUE TITLE
Support the new tvOS13 TabBar

### ISSUE THREAD

**Issue by hufkens** [react-native-tvos/react-native-tvos#17]
The following behaviour seems to be broken in the new UITabBar on tvOS13. Selecting the 

In tvOS, swiping down from the tab bar moves focus into the content view; specifically, to the first focusable view that is visually below the selected tab. Swiping down behaves like a normal focus-changing gesture—that is, focus moves in the direction the user swiped. If nothing is focusable immediately below the selected tab, the closest focusable view is focused instead. In iOS, the tab bar always remains in focus at the bottom of the screen.

React Native version:
```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.37 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native-tvos:  0.60.4-6 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

**Comment by dlowder-salesforce** [comment]
Thanks @hufkens .... I am definitely seeing issues with UITabBar in iOS 13.  Investigating.

**Comment by dlowder-salesforce** [comment]
Seems that what you have to do is press the button on the Siri remote after focusing a tab bar item, then the appearance of the item changes, and focus can move to the content.  Maybe this is the new expected behavior on tvOS 13.

The other big issue I'm seeing is slow rendering of new content when navigating between tab bar items.... having a look at that next.

**Comment by hufkens** [comment]
It works indeed when you press. But it should work when you swipe down too. I checked Apple’s TV app and that works. 

No idea why this stopped working.

**Comment by dlowder-salesforce** [comment]
The behavior and the API of UITabBar has changed so much in iOS/tvOS 13, that it may as well be regarded as a completely new UI.  Besides the focus problem we're seeing, the appearance is now controlled by a new API, and the appearance properties used in RN TabBarIOS are now marked "legacy".

Since RN core has dropped TabBarIOS for the phone anyway, I think the best path forward is to create a new "TVOSTabBar" view manager specifically for iOS 13 and later.

**Comment by hufkens** [comment]
I looked into the appearance API and the depricated can still be used for the old version. And we can add the new properties without breaking the old behaviour. I need it anyway for our app, so I'll contribute it back to this repo. Why the swipe down isn't working I'll also try to investigate.

**Comment by dlowder-salesforce** [comment]
Found a very simple pure native example project for UITabBarController, and modified it for tvOS at https://github.com/dlowder-salesforce/TabBarFromCode .

I do see that this project doesn't have the problem of swiping down from the tab bar to the content.  However, even this very simple project has severe performance issues -- takes almost a second to switch tabs, and I'm seeing glitches where it switches back and forth between tabs during the transition.

I'm starting to wonder whether we should support this API or not.

**Comment by hufkens** [comment]
Apple is pushing this TabBar very hard and doesn’t really like apps using different forms like a sidebar. Maybe the SwipeDown is an issue because of our setup. So I’ll have to dig into that. 

For performance, did you try on a real device because that seems reasonable here.

**Comment by brodybits** [comment]
??

**Comment by Teamgamer44** [comment]
Hey there, is there any progress for this issue?
I think many of us would like have this feature to use the 
UITabBar in React Native. I spent also many times
to implement this in my project but my Apple TV does not render it.
Are there some alternatives, or using it by platform channels (using swift code directly)?

**Comment by dlowder-salesforce** [comment]
@Teamgamer44 there has been no recent progress on this.  Once I get a new 0.61.5 release out with some bug fixes, and then a 0.62 release, I will come back to this.  I think this could certainly be implemented natively in Swift, where Swift shows the RN view controller for the tab contents.

**Comment by zth** [comment]
Reviving this issue again - has anyone gotten further on this, either trying to fix it centrally here, or by themselves outside of this project?

Thanks! 😃

**Comment by vvdodiya** [comment]
Hello
Is there any update for the support tab bar in tvOS? I have implemented a tab bar in my tvOS app but can not focus on the tab.

**Comment by adkaushik** [comment]
The tab bar comes into focus when menu button on the remote is clicked. However, when the component rendered in the tab take long time to render, the selected tab jumps to the first tab and flickers repeatedly.

Found this old related [issue](https://github.com/facebook/react-native/issues/15081)  in react native, which is still happening when using the tabbarios component in  tvos

**Comment by douglowder** [comment]
In testing the latest release of this repo (0.66.3-0) with tvOS 15.2, it seems that all of the issues with the `TabBarIOS` component have been resolved. Swiping down from the tab bar works normally now. So I'm closing this issue.

**Comment by ketanPRO** [comment]
@douglowder It seems TabBarIOS is working fine with apple tv now. But why is react native deprecating this while there is no alternative of this one.

**Comment by douglowder** [comment]
RN core does not support TV. Apple TV is the only platform that really needs this API so it is only available here.

I should note that I have not yet implemented this API for the new Fabric architecture.... 😬

**Comment by soj** [comment]
Hi there!  

I tried to use TabBarIOS but I don't understand how to use it with multiple Stack navigation together. I even created a question on StackOverflow. Can you from me a hint, please? Thanks!

**Comment by douglowder** [comment]
@soj `TabBarIOS` is a wrapper around the `UITabBar` and friends, available only on iOS and tvOS. The tvOS implementation is quite different from iOS, and is basically set up so the tab bar has to wrap everything else in the view tree.

You can try it, but you would almost certainly have to use `@react-navigation/stack`, not `@react-navigation/native-stack`, and even then I'm not sure how it would really behave.

If you are using React Navigation anyway, I would use their header implementation and forget about the native tab bar.
