### ISSUE TITLE
General Lag in Focusing and Navigation Across the React Native TV Application

### ISSUE THREAD

**Issue by saadlatif75** [react-native-tvos/react-native-tvos#798]
I am encountering a significant lag when navigating and focusing on various components throughout my React Native TV application. The lag affects the user experience across the entire app, making it difficult for users to interact with UI elements smoothly.
Environment:

React Native Version: npm:react-native-tvos@0.73.6-1
Platform: Android TV 
Steps to Reproduce:

Launch the application on a TV device.
Navigate to the PlaylistMovieDetail component.
Attempt to focus on the elements within this component.
Switch focus to the EpgDetailTable component.
Observe the delay in focus transitions.
Expected Behavior: The focus should switch seamlessly between components without noticeable lag.

**Actual Behavior:** There is a significant delay when changing focus between the components, causing frustration for users.
  <KeyboardAvoidingView style={commonContainerStyle} behavior="padding">
      <View style={styles.mainContainer}>
        <View style={styles.leftContainer}>
          <Drawer
            sections={filteredSections}
            onSubMenuPress={handleSubMenuPress}
            renderListHeader={renderListHeader()}
            renderListEmpty={renderListEmpty}
            onMainMenuPress={handleMainMenuPress}
          />
        </View>
        {secondaryDrawerState.tv ? (
          <SecondaryDrawer
            data={tvShowsResponse}
            onSubMenuPress={item => {
              setSelectedCategory(item.category_name);
              setSelectedcategoryId(item?.category_id);
              setTvPlayListHomeScreen(true);
            }}
            headerText={headerText}
            liveCategoryLoader={liveCategoryLoader}
          />
        ) : null}
        {secondaryDrawerState.movies ? (
          <SecondaryDrawer
            data={movieResponse}
            onSubMenuPress={item => {
              // setSelectedCategory(item.category_name);
              // setSelectedcategoryId(item?.category_id);
              setCenterDetail({movieDetail: true});
              setTvPlayListHomeScreen(false);
            }}
            headerShown={false}
            movieHeaderShown={true}
            // headerText={headerText}
            liveCategoryLoader={liveCategoryLoader}
          />
        ) : null}
        <XstreamAddPlaylistModal
          visible={isModalVisible}
          onClose={() => dispatch(hideModal())}
        />
        {tvPlayListHomeScreen ? (
          <ScrollView contentContainerStyle={{flex: 1}}>
            <PlaylistMovieDetail
              selectedProgram={selectedProgram}
              username={username}
              password={password}
              serverAddress={serverurl}
              streamId={selectedChannelStreamId}
            />
            <EpgDetailTable
              epgData={programs}
              channels={streams}
              streamsLoader={streamsLoader}
              autoFocused={tvPlayListHomeScreen}
            />
          </ScrollView>
        ) : null}
        {centerDetail.movieDetail ? (
          <ScrollView>
            <MovieDetailSection />
            <CenterData
              data={dataFavouriteMovie}
              imageStyle={{
                height: heightPixel(150),
              }}
              imageMainContainerStyle={{
                height: heightPixel(176),
                borderWidth: 0,
              }}
              leftRightArrow={false}
              chipData={movieData}
              pillVisible
              isMovieCard={true}
              // title={"Favorite's"}
            />
            <MovieDetailCard data={dataFavouriteMovie} />
          </ScrollView>
        ) : null}
        {!tvPlayListHomeScreen && !centerDetail.movieDetail ? (
          <ScrollView
            contentContainerStyle={{
              flex: rightdrawervisibility ? 1 : null,
            }}>
            {rightdrawervisibility ? (
              <ImageBackground
                source={commonIcons.ic_tv_rectangle}
                style={styles.rightSideDrawerWrapper}>
                <View style={styles.rightSideDrawerHeader}>
                  <TouchableOpacity
                    onPress={() => {
                      setRightDrawerVisibility(!rightdrawervisibility);
                    }}>
                    <Image
                      resizeMode="contain"
                      style={styles.arrowLeft}
                      source={commonIcons.ic_white_arrow_left}
                    />
                  </TouchableOpacity>
                  <Text style={styles.homeSettingText}>Home Setting</Text>
                </View>
                <View style={styles.SecondHalfRightDrawer}>
                  <TouchableOpacity
                    style={styles.rightItem}
                    onPress={() => {
                      onToggleSwitch();
                    }}>
                    <Image
                      resizeMode="contain"
                      style={styles.starIcon}
                      source={commonIcons.ic_small_star}
                    />
                    <Text style={styles.favouriteAppText}>Favourtie apps</Text>

                    <Switch
                      value={isSwitchOn}
                      onValueChange={onToggleSwitch}
                      color={appColor.skyblue100}
                    />
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={styles.rightItem}
                    onPress={() => {
                      onToggleSwitch();
                    }}>
                    <Image
                      resizeMode="contain"
                      style={styles.starIcon}
                      source={commonIcons.ic_small_movie}
                    />
                    <Text style={styles.favouriteAppText}>Recording</Text>

                    <Switch
                      value={isSwitchOn}
                      onValueChange={onToggleSwitch}
                      color={appColor.skyblue100}
                    />
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={styles.rightItem}
                    onPress={() => {
                      onToggleSwitch();
                    }}>
                    <Image
                      resizeMode="contain"
                      style={styles.starIcon}
                      source={commonIcons.small_ic_youtube}
                    />
                    <Text style={styles.favouriteAppText}>youtube</Text>

                    <Switch
                      value={isSwitchOn}
                      onValueChange={onToggleSwitch}
                      color={appColor.skyblue100}
                    />
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={styles.rightItem}
                    onPress={() => {
                      onToggleSwitch();
                    }}>
                    <Image
                      resizeMode="contain"
                      style={styles.starIcon}
                      source={commonIcons.ic_small_netflix}
                    />
                    <Text style={styles.favouriteAppText}>Netflix</Text>

                    <Switch
                      value={isSwitchOn}
                      onValueChange={onToggleSwitch}
                      color={appColor.skyblue100}
                    />
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={styles.rightItem}
                    onPress={() => {
                      onToggleSwitch();
                    }}>
                    <Image
                      resizeMode="contain"
                      style={styles.starIcon}
                      source={commonIcons.ic_small_prime}
                    />
                    <Text style={styles.favouriteAppText}>Prime</Text>

                    <Switch
                      value={isSwitchOn}
                      onValueChange={onToggleSwitch}
                      color={appColor.skyblue100}
                    />
                  </TouchableOpacity>
                </View>
              </ImageBackground>
            ) : getMoreAppModalVisibility ? (
              <ImageBackground source={commonIcons.ic_tv_rectangle}>
                <View style={[styles.appMainModalContainer]}>
                  <View style={styles.appModalContainer}>
                    <Text style={styles.getMoreAppText}>Get More apps</Text>
                    <TouchableOpacity
                      onPress={() => {
                        setGetMoreAppModalVisibility(
                          !getMoreAppModalVisibility,
                        );
                        setRightDrawerVisibility(false);
                      }}
                      style={styles.crossIconButton}>
                      <Image
                        style={{width: 14, height: 14}}
                        resizeMode="contain"
                        source={commonIcons.ic_cross}
                      />
                    </TouchableOpacity>
                  </View>
                  <View style={styles.googleButtonContainer}>
                    <TouchableOpacity style={styles.buttonContainer}>
                      <Image
                        style={styles.commonButtonIcon}
                        source={commonIcons.ic_google}
                      />
                      <Text style={styles.googlePlayText}>
                        Google Play Store
                      </Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.buttonContainer}>
                      <Image
                        style={styles.commonButtonIcon}
                        source={commonIcons.ic_android}
                      />
                      <Text style={styles.googlePlayText}>
                        Aptoid App Store
                      </Text>
                    </TouchableOpacity>
                  </View>
                  <ScrollView
                    contentContainerStyle={{marginVertical: 10}}
                    horizontal
                    showsHorizontalScrollIndicator={false}>
                    {appdata.map(item => {
                      return (
                        <TouchableOpacity style={{}}>
                          <Image source={item?.image} />
                        </TouchableOpacity>
                      );
                    })}
                  </ScrollView>
                  <CenterData
                    data={data}
                    imageProps={{resizeMode: 'contain'}}
                    backgroundColor="rgba(21, 75, 160, 0)"
                    topTitleVisible={false}
                    borderColorCode={'white'}
                  />
                  <CenterData
                    data={data}
                    imageProps={{resizeMode: 'contain'}}
                    backgroundColor="rgba(21, 75, 160, 0)"
                    topTitleVisible={false}
                    borderColorCode={'white'}
                  />
                </View>
              </ImageBackground>
            ) : (
              <View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={data}
                    title={'Favorite Apps'}
                    imageProps={{resizeMode: 'contain'}}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                  />
                </View>

                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataContinueWatching}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    title={'Continue Watching'}
                  />
                </View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataFavouriteMovie}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    pillIcVisible
                    chipData={chipData}
                    pillVisible
                    title={"Favorite's"}
                  />
                </View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataContinueWatching}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    chipData={chipRecordingData}
                    pillVisible
                    title={'Recordings'}
                  />
                </View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataSportWatching}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    chipData={showAndSportData}
                    pillVisible
                    title={'Curated Shows & Sports'}
                  />
                </View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataSportWatching}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    chipData={showAndSportData}
                    title={'YouTube Recommendations'}
                  />
                </View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataFavouriteMovie}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    chipData={showAndSportData}
                    title={'Netflix'}
                  />
                </View>
                <View style={styles.centerContainer}>
                  <CenterData
                    data={dataContinueWatching}
                    imageStyle={{
                      height: heightPixel(150),
                    }}
                    imageMainContainerStyle={{
                      height: heightPixel(176),
                      borderWidth: 0,
                    }}
                    chipData={showAndSportData}
                    title={'Amazon Prime'}
                  />
                </View>
              </View>
            )}
          </ScrollView>
        ) : null}
      </View>
    </KeyboardAvoidingView>

import React, {useState} from 'react';
import {
  TouchableHighlight,
  View,
  Text,
  StyleSheet,
  Image,
  Pressable,
} from 'react-native';
import {appColor} from '../../utils/ColorScheme';

const DrawerItem = ({title, onPress, img, imageDown, onFocus, onBlur}) => {
  const [isFocused, setIsFocused] = useState(false);

  const handleFocus = () => {
    setIsFocused(true);
    // onFocus();
  };

  const handleBlur = () => {
    setIsFocused(false);
    // onBlur();
  };

  return (
    <Pressable
      onPress={onPress}
      style={({focused, pressed}) => [
        styles.touchable,
        focused && styles.focused,
      ]}>
      {({focused}) => (
        <View style={styles.container}>
          <Image
            source={img}
            style={[styles.icon, focused && {tintColor: appColor.skyblue100}]}
          />
          <Text style={[styles.title, focused && styles.focusedText]}>
            {title}
          </Text>
          {imageDown && <Image source={imageDown} style={styles.imageDown} />}
        </View>
      )}
    </Pressable>
  );
};

export default DrawerItem;

    
    const CELL_WIDTH = 200;
const CELL_HEIGHT = 50;

const EpgDetailTable = ({
  channels,
  epgData = [],
  streamsLoader,
  autoFocused,
}: {
  streamsLoader: boolean;
  autoFocused: boolean;
}) => {
  const dispatch = useDispatch();
  const timeSlotListRef = useRef(null);
  const channelRef = useRef();
  const selectedChannelStreamId = useSelector(
    state => state.epg.selectedChannelStreamId,
  );
  // Group EPG data by channel_id for easy access
  const epgDataByChannel = useMemo(() => {
    return epgData.reduce((acc, program) => {
      const {channel_id} = program;
      if (!acc[channel_id]) acc[channel_id] = [];
      acc[channel_id].push(program);
      return acc;
    }, {});
  }, [epgData]);

  // Extract unique time slots from epgData
  // const timeSlots = useMemo(() => {
  //   const times = epgData.map(item => item.start);
  //   const uniqueTimes = [...new Set(times)].sort();
  //   return uniqueTimes.map(time =>
  //     moment(time.slice(0, 14), 'YYYYMMDDHHmmss').format('h:mm A'),
  //   );
  // }, [epgData]);

  const timeSlots = useMemo(() => {
    const userTimeZone = moment.tz.guess(); // Get user's device time zone

    const times = epgData.map(item => item.start);
    const uniqueTimes = [...new Set(times)].sort();

    return uniqueTimes.map(time => {
      // Parse the input time string to create a moment object in UTC
      const utcTime = moment.utc(time.slice(0, 14), 'YYYYMMDDHHmmss');

      // Convert to the user's time zone
      const localTime = utcTime.tz(userTimeZone);

      // Return the formatted time string
      return localTime.format('h:mm A');
    });
  }, [epgData]);

  const handlePress = (payload, programIndex) => {
    // Dispatch the selected program
    dispatch(setSelectedProgram(payload));

    // Auto-scroll the time slots based on the selected program's index
    const offset = programIndex * CELL_WIDTH;
    if (timeSlotListRef.current) {
      timeSlotListRef.current.scrollToOffset({offset, animated: true});
    }
  };

  const renderProgramCell = (program, programIndex) => {
    return (
      <Pressable
        key={program?.id || 'no-program'}
        onFocus={() =>
          handlePress(
            program
              ? {
                  title: program.title,
                  description: program.desc,
                  programData: program,
                }
              : {message: 'No Program Found'},
            programIndex,
          )
        }
        onPress={() =>
          handlePress(
            program
              ? {title: program.title, description: program.desc}
              : {message: 'No Program Found'},
            programIndex,
          )
        }
        style={({pressed, focused}) => [
          styles.programCell,
          (pressed || focused) && styles.focusedItem,
        ]}>
        <Text style={styles.programText}>
          {program?.title ? program.title : 'No Program Found'}
        </Text>
      </Pressable>
    );
  };
  const handleChannelPressed = stream_id => {
    dispatch(setselectedChannelStreamId(stream_id));
    if (channelRef.current) {
      // Use the ref to focus the component again
      channelRef?.current?.focus();
    }
  };

  const renderChannelRow = ({item: channel, index}) => {
    const {epg_channel_id, stream_icon, name, stream_id} = channel;
    const programs = epgDataByChannel[epg_channel_id] || [];

    return (
      <View style={styles.rowContainer}>
        {/* Channel Column */}
        <Pressable
          ref={channelRef}
          style={({pressed, focused}) => [
            styles.channelColumn,
            (pressed || focused) && styles.focusedItem,
          ]}
          onPress={() => handleChannelPressed(stream_id)}>
          <Image
            resizeMode="contain"
            source={stream_icon ? {uri: stream_icon} : commonIcons.ic_disney}
            style={styles.image}
          />
          <Text style={styles.channelText}>{name}</Text>

          {selectedChannelStreamId == stream_id ? (
            <LottieView
              style={{width: 24, height: 24}}
              source={require('../../assests/nowPlaying.json')}
              autoPlay
              loop
            />
          ) : null}
        </Pressable>

        {/* Program Cells */}
        <FlatList
          data={programs.length > 0 ? programs : [{}]} // If no programs, pass an empty object to render "No Program Found"
          renderItem={({item, index}) => renderProgramCell(item, index)}
          keyExtractor={(item, index) => item.id || `no-program-${index}`}
          horizontal
          showsHorizontalScrollIndicator={false}
          initialNumToRender={5}
          maxToRenderPerBatch={5}
          windowSize={5}
        />
      </View>
    );
  };

  const renderHeader = () => {
    return (
      <View style={styles.headerContainer}>
        <View style={styles.channelHeader}>
          <Text style={styles.headerText}>Channel</Text>
        </View>
        <FlatList
          ref={timeSlotListRef}
          data={timeSlots}
          renderItem={({item}) => (
            <View style={styles.timeSlotHeader}>
              <Text style={styles.headerText}>{item}</Text>
            </View>
          )}
          keyExtractor={(item, index) => `timeslot-${index}`}
          horizontal
          showsHorizontalScrollIndicator={false}
        />
      </View>
    );
  };

  return (
    <View style={styles.container}>
      {streamsLoader ? (
        <ActivityIndicator size="large" color="white" />
      ) : (
        <>
          {renderHeader()}
          <FlashList
            data={channels}
            renderItem={renderChannelRow}
            keyExtractor={item => item?.stream_id?.toString()}
            initialNumToRender={10}
            windowSize={5}
            maxToRenderPerBatch={10}
            updateCellsBatchingPeriod={50}
            removeClippedSubviews={true}
            showsVerticalScrollIndicator={false}
          />
        </>
      )}
    </View>
  );
};

**Comment by douglowder** [comment]
In order to help you, we would need to have the following:

- a link to a repository containing a complete application project that can reproduce the issue
- detailed steps for setting up the app, including dependencies and any backend authentication needed
- steps to actually see the performance issue you are having

The code above is not sufficient, as it is not formatted in an understandable way, and there is no indication as to how that code fits into the entire application, or what the application's package dependencies are.

**Comment by ChadyAyoub4** [comment]
I have noticed this as well, this happens when building for simulator TVOs 18, using Xcode 16, building the same code on TVOS 17.5 will work normally without any lag or focus issues, even reanimated animations seem to perform worse when building for TVOS 18

**Comment by douglowder** [comment]
> @douglowder I have noticed this as well, this happens when building for simulator TVOs 18, using Xcode 16, building the same code on TVOS 17.5 will work normally without any lag or focus issues, even reanimated animations seem to perform worse when building for TVOS 18

@ChadyAyoub4 this is very interesting... does this also happen on real tvOS 18 devices? Might be a simulator bug. I'll look into this.

**Comment by ChadyAyoub4** [comment]
@douglowder, im not sure yet, i will need to test a few cases: Building for TVOS 17.5 using xcode 15.4 and then testing on a TVOS 18 device, and the same but building for TVOS 18 using xcode 16, To make sure if it is an xcode build issue or an OS specific issue, will try soon and let you know my findings

**Comment by ChadyAyoub4** [comment]
@douglowder I just tested on Real device, The issue appears to be a TVOS 18 and not Xcode 16. I tested on a build built using xcode 15.4 with target os set to 17.5 and it was lagging on the os 18.

**Comment by saadlatif75** [comment]
@douglowder @ChadyAyoub4  I'm developing an app similar to Tivimate that utilizes an electronic program guide (EPG). The app downloads an XML file at startup, processes the data, and I’ve been trying to use various packages like RNFS and react-native-fetch-blob to read the file. However, I've encountered crashes due to memory leaks.

To address this, I've implemented native code to convert the XML to JSON and store the data in an SQLite database. While this approach allows me to read data in chunks on the React Native side, I’m still experiencing lag, which impacts the user experience.

I want to implement a prefetching strategy for the program data from the SQLite database to minimize lag and enhance the overall performance. Any suggestions or best practices for optimizing this process would be greatly appreciated!

**Comment by kosso** [comment]
Just to add to this: I just did some tests on the tvOS18 simulator for an interface I'm building with a lot of focusable items on screen and did not find any issues with focus transition lagging when testing on tvOS 17 and tvOS 18 Simulators. ( demo video: https://www.youtube.com/watch?v=do8PXYH5ITY )

However, I wanted to point out that I'm not using any TouchableOpacity wrappers at all, since I want more control over how the focus looks. (I do it using a useRef which tracks the currently focused Pressable on a screen, then style props are modified according to that.)

I noticed extensive use of TouchableOpacity in the OP sample code.

**Comment by douglowder** [comment]
I'm going to close this, as it appears to be specific to TouchableOpacity and not reproducible on Pressable.

**Comment by ChadyAyoub4** [comment]
@douglowder, i am still encountering this issue even after using pressable. i will send more details

**Comment by douglowder** [comment]
Thanks for the update! This is a great find.

**Comment by ChadyAyoub4** [comment]
@douglowder is it possible to reopen this issue pls? As it is not related to the use of Touchable opacity or pressable

**Comment by douglowder** [comment]
I believe this is very likely fixed by #859 . @ChadyAyoub4 or @saadlatif75 if you could try RNTV 0.76.7-0 or 0.77.0-0 or later, and see if the problem is resolved for you. If not, please add a comment here and I will reopen the issue.

**Comment by chadyayoub** [comment]
@douglowder I have tested it in RN 0.78 and can confirm that it has been fixed
